services:
  coffee-ctl:
    image: mfreudenberg/coffee-ctl:latest
    build: .
    volumes:
      - type: bind
        source: ./config.yaml
        target: /config.yaml
        read_only: true
    environment:
      MQTT_BROKER_URL:
      MQTT_BROKER_USERNAME:
      MQTT_BROKER_PASSWORD:
      REDIS_URL:
      GIN_MODE: release
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    hostname: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      retries: 1000
      timeout: 2s
